### ISSUE TITLE
Error when play .wav and .mp3

### ISSUE THREAD

**Issue by Doughboy02** [mobiletechtracker/NetCoreAudio#5] opened 2019-07-26 03:25 UTC
I get an error whenever trying to run the line
`Player.Play(filePath).GetAwaiter().GetResult();`

Error
`Error executing MCI command 'Status C:\Users\Panda\source\repos\TextToSpeechApi\TextToSpeechApi\bin\Debug\netcoreapp2.1\Voices\testing sound.mp3 Length'. Error code: 310. Message: Specify a device or driver name that is less than 79 characters.`

Wasn't sure if this was the same error that has already been posted considering the Error code is different...

**Comment by MortenChristiansen** [comment] 2019-07-26 08:22
Have you tried using a relative path?

**Comment by fiodarsazanavets** [comment] 2019-09-01 16:15
On Windows, there is a hard limit on the number of characters you can use in the path or audio device alias in the media interface. As suggested, please use a relative path.

**Comment by fiodarsazanavets** [comment] 2019-09-01 16:16
Closing since this issue is caused by the limitation of Windows media interface and not the library itself.

**Closed by fiodarsazanavets** 2019-09-01 16:16 UTC
